### PR TITLE
Replace Debug with Console.WriteLine for messages

### PR DESCRIPTION
**Pull request by edleno2**
## Description

Replaced Debug.WriteLine with Console.WriteLine in UnitTestLauncher

## Motivation and Context

Use of Debug required that UnitTestLauncher be built in Debug mode before putting into the Nuget repository.  This change will allow Release builds to be put into the Nuget repository.  Changes to mscorlib to allow access to the internal System.Console class have already been made.

- Fixes nanoFramework/Home#738

## How Has This Been Tested?

Tested by running the unit tests in Visual studio.  Output was checked in the Tests output window of Visual Studio 2019.  First tested current code and confirmed that a debug build will display the messages, but a release build did not display the messges.  After changing verified that both Debug and Release produced output in the Tests output window.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Ellerbach** [comment]
@josesimoes is Console still present in nano? And are we sure the mechanism used behind is not using Debug and won't get removed from the compilation in Release?

**Comment by Ellerbach** [comment]
Btw, that will apply to the Logging Framework as well.

**Review by josesimoes — APPROVED** [review]
Perfect! Thanks.

**Comment by josesimoes** [comment]
> @josesimoes is Console still present in nano? And are we sure the mechanism used behind is not using Debug and won't get removed from the compilation in Release?

Yes. It wont' be removed on Release build and the output will show in the debugger channel as expected!

**Comment by josesimoes** [comment]
> Btw, that will apply to the Logging Framework as well.

Yes, that was already taken care of with this: nanoframework/nanoFramework.Logging#10

**Pull request merged**
